export {
  applyDataDetectors,
  getRegisteredDataDetectors,
  TextTemplateProcessor,
  XmlTemplateParser,
  XmlTemplateProcessor,
  XmlTemplateSerializer,
  type IDataDetector,
  registerDataDetector,
  type ITextTemplateProcessor,
  type MissingKeyBehavior,
  type TemplateBlockContentModel,
  type TemplateBlockExpansionContext,
  type TemplateBlockNode,
  type TemplateBlockProvider,
  type TemplateDocument,
  type TemplateNode,
  type TemplateTextNode,
  type TextTemplateOptions,
  registerTextTemplateBlockProvider,
  unregisterDataDetector,
  unregisterTextTemplateBlockProvider,
  haveRegisteredTextTemplateBlockProvider,
  getRegisteredTextTemplateBlockProviders,
} from "./template-processor";
export {
  EmailDetector,
  EmojiDetector,
  PhoneNumberDetector,
  UrlDetector,
} from "./data-detectors";
