export {
  TextTemplateProcessor,
  XmlTemplateParser,
  XmlTemplateProcessor,
  XmlTemplateSerializer,
  type ITextTemplateProcessor,
  type MissingKeyBehavior,
  type TemplateBlockContentModel,
  type TemplateBlockExpansionContext,
  type TemplateBlockNode,
  type TemplateBlockProvider,
  type TemplateDocument,
  type TemplateNode,
  type TemplateTextNode,
  type TextTemplateOptions,
  registerTextTemplateBlockProvider,
  unregisterTextTemplateBlockProvider,
  haveRegisteredTextTemplateBlockProvider,
  getRegisteredTextTemplateBlockProviders,
} from "./template-processor";
