export {
  TextTemplateProcessor,
  XmlTemplateParser,
  XmlTemplateProcessor,
  XmlTemplateSerializer,
  type ITextTemplateDirective,
  type ITextTemplateProcessor,
  type MissingKeyBehavior,
  type TemplateBlockContentModel,
  type TemplateBlockExpansionContext,
  type TemplateBlockNode,
  type TemplateBlockProvider,
  type TemplateDocument,
  type TemplateNode,
  type TemplateTextNode,
  type TextTemplateOptions,
  registerTextTemplateBlockProvider,
  unregisterTextTemplateBlockProvider,
  haveRegisteredTextTemplateBlockProvider,
  getRegisteredTextTemplateBlockProviders,
  registerTextTemplateDirective,
  unregisterTextTemplateDirective,
  haveRegisteredTextTemplateDirective,
  getRegisteredTextTemplateDirectives,
} from "./template-processor";
