import type { EmojiCategory, EmojiSearchTerms } from "./emoji-picker.types";

/** English search metadata for the built-in emoji set. */
export const DEFAULT_EN_US_EMOJI_SEARCH_TERMS: EmojiSearchTerms = {
  // Smileys and people
  "😀": ["grinning", "smile", "happy", "face"],
  "😁": ["beaming", "smile", "happy", "face"],
  "😂": ["joy", "laugh", "tears", "face"],
  "🤣": ["rofl", "rolling", "laugh", "face"],
  "😃": ["smile", "happy", "face"],
  "😄": ["smile", "happy", "face"],
  "😅": ["sweat smile", "relief", "face"],
  "😆": ["laugh", "squint", "face"],
  "😉": ["wink", "winking", "face"],
  "😊": ["smile", "blush", "happy", "face"],
  "😋": ["yum", "delicious", "face"],
  "😎": ["cool", "sunglasses", "face"],
  "😍": ["heart eyes", "love", "smile", "face"],
  "😘": ["kiss", "love", "face"],
  "🥰": ["love", "hearts", "smile", "face"],
  "🤗": ["hug", "hugging", "face"],
  "🤔": ["thinking", "think", "face"],
  "😐": ["neutral", "meh", "face"],
  "🙄": ["eye roll", "annoyed", "face"],
  "😏": ["smirk", "smug", "face"],
  "😒": ["unamused", "annoyed", "face"],
  "😔": ["sad", "pensive", "face"],
  "😕": ["confused", "face"],
  "🙃": ["upside down", "silly", "face"],
  "😢": ["cry", "sad", "tear", "face"],
  "😭": ["cry", "tears", "sad", "face"],
  "😡": ["angry", "mad", "rage", "face"],
  "😠": ["angry", "mad", "face"],
  "😱": ["scream", "shocked", "scared", "face"],
  "😴": ["sleep", "tired", "face"],
  "🤯": ["mind blown", "exploding head", "shocked"],
  "🥳": ["party", "celebration", "birthday", "face"],
  "🥺": ["pleading", "sad", "face"],
  "😈": ["devil", "smiling devil", "evil"],
  "👿": ["devil", "angry devil", "evil"],
  "👋": ["wave", "hello", "goodbye", "hand"],
  "👌": ["ok", "okay", "perfect", "hand"],
  "✌️": ["peace", "victory", "hand"],
  "🤞": ["fingers crossed", "luck", "hope"],
  "👍": ["thumbs up", "like", "approve", "yes"],
  "👎": ["thumbs down", "dislike", "no"],
  "👏": ["clap", "applause", "bravo"],
  "🙌": ["raised hands", "celebrate", "praise"],
  "🙏": ["pray", "thanks", "please", "namaste"],
  "💪": ["muscle", "strong", "strength"],

  // Animals and nature
  "🐶": ["dog", "puppy", "animal"],
  "🐱": ["cat", "kitten", "animal"],
  "🐭": ["mouse", "animal"],
  "🐰": ["rabbit", "bunny", "animal"],
  "🦊": ["fox", "animal"],
  "🐻": ["bear", "animal"],
  "🐼": ["panda", "animal"],
  "🐸": ["frog", "animal"],
  "🐵": ["monkey", "animal"],
  "🦁": ["lion", "animal"],
  "🐮": ["cow", "animal"],
  "🐷": ["pig", "animal"],
  "🐔": ["chicken", "bird", "animal"],
  "🐧": ["penguin", "bird", "animal"],
  "🐦": ["bird", "animal"],
  "🐝": ["bee", "insect", "animal"],
  "🦋": ["butterfly", "insect", "animal"],
  "🐢": ["turtle", "animal"],
  "🐍": ["snake", "animal"],
  "🐙": ["octopus", "animal"],
  "🐬": ["dolphin", "animal"],
  "🦈": ["shark", "animal"],
  "🌸": ["cherry blossom", "flower", "spring"],
  "🌹": ["rose", "flower", "love"],
  "🌻": ["sunflower", "flower", "sun"],
  "🌈": ["rainbow", "pride", "weather"],
  "☀️": ["sun", "sunny", "weather"],
  "🌙": ["moon", "night", "weather"],
  "⭐": ["star", "favorite", "favourite"],
  "✨": ["sparkles", "shine", "magic"],

  // Food and drink
  "🍎": ["apple", "fruit", "red apple"],
  "🍌": ["banana", "fruit"],
  "🍓": ["strawberry", "fruit"],
  "🍉": ["watermelon", "fruit"],
  "🍔": ["burger", "hamburger", "food"],
  "🍟": ["fries", "chips", "food"],
  "🍕": ["pizza", "food"],
  "🌮": ["taco", "food"],
  "🍣": ["sushi", "food"],
  "🍰": ["cake", "dessert"],
  "🎂": ["birthday", "cake", "celebration"],
  "🍫": ["chocolate", "candy"],

  // Travel and places
  "🚗": ["car", "automobile", "drive"],
  "🚌": ["bus", "travel"],
  "🚲": ["bicycle", "bike", "cycle"],
  "✈️": ["airplane", "plane", "flight", "travel"],
  "🚀": ["rocket", "launch", "ship"],
  "🚁": ["helicopter", "flight"],
  "🚢": ["ship", "boat", "travel"],
  "🏠": ["house", "home"],
  "🏡": ["house", "home", "garden"],
  "🏖️": ["beach", "holiday", "vacation"],
  "🏔️": ["mountain", "snow", "travel"],
  "🏕️": ["camping", "tent", "outdoors"],

  // Activities and objects
  "⚽": ["football", "soccer", "sport"],
  "🏀": ["basketball", "sport"],
  "🏆": ["trophy", "winner", "award"],
  "🎨": ["art", "paint", "palette"],
  "🎵": ["music", "note", "song"],
  "🎮": ["game", "gaming", "controller"],
  "📱": ["phone", "mobile", "cellphone"],
  "💻": ["computer", "laptop", "work"],
  "📷": ["camera", "photo", "picture"],
  "📸": ["camera", "photo", "flash"],
  "💡": ["idea", "light bulb", "light"],
  "🔒": ["lock", "secure", "private"],
  "🔑": ["key", "password", "unlock"],
  "📌": ["pin", "pushpin", "location"],
  "📧": ["email", "mail", "envelope"],
  "💰": ["money", "cash", "bag"],
  "💳": ["credit card", "payment", "money"],
  "💎": ["diamond", "gem", "jewel"],

  // Symbols and flags
  "❤️": ["heart", "love", "red"],
  "💔": ["broken heart", "heart", "sad"],
  "🔥": ["fire", "flame", "hot"],
  "🎉": ["party", "celebration", "tada"],
  "✅": ["check", "done", "yes", "success"],
  "❌": ["cross", "cancel", "no", "error"],
  "⚠️": ["warning", "alert", "caution"],
  "❓": ["question", "help"],
  "❗": ["exclamation", "important", "alert"],
  "💯": ["hundred", "perfect", "score"],
  "🇺🇸": ["united states", "usa", "america", "flag"],
  "🇬🇧": ["united kingdom", "uk", "britain", "england", "flag"],
  "🇳🇱": ["netherlands", "holland", "dutch", "flag"],
  "🇨🇦": ["canada", "canadian", "flag"],
  "🇩🇪": ["germany", "german", "deutschland", "flag"],
  "🇫🇷": ["france", "french", "flag"],
  "🇪🇸": ["spain", "spanish", "flag"],
  "🇯🇵": ["japan", "japanese", "flag"],
  "🇨🇳": ["china", "chinese", "flag"],
  "🇰🇷": ["korea", "south korea", "korean", "flag"],
  "☕": ["coffee", "tea", "drink"],
};

/**
 * Default comprehensive set of emoji categories.
 *
 * Provides a curated selection of commonly-used emoji organised
 * into eight standard categories.
 */
const DEFAULT_EMOJI_CATEGORY_DATA: readonly EmojiCategory[] = [
  {
    name: "Smileys & People",
    emojis: [
      "😀",
      "😁",
      "😂",
      "🤣",
      "😃",
      "😄",
      "😅",
      "😆",
      "😉",
      "😊",
      "😋",
      "😎",
      "😍",
      "😘",
      "🥰",
      "😗",
      "😙",
      "😚",
      "🙂",
      "🤗",
      "🤩",
      "🤔",
      "🤨",
      "😐",
      "😑",
      "😶",
      "🙄",
      "😏",
      "😣",
      "😥",
      "😮",
      "🤐",
      "😯",
      "😪",
      "😫",
      "🥱",
      "😴",
      "😌",
      "😛",
      "😜",
      "😝",
      "🤤",
      "😒",
      "😓",
      "😔",
      "😕",
      "🙃",
      "🤑",
      "😲",
      "🙁",
      "😖",
      "😞",
      "😟",
      "😤",
      "😢",
      "😭",
      "😦",
      "😧",
      "😨",
      "😩",
      "🤯",
      "😬",
      "😰",
      "😱",
      "🥵",
      "🥶",
      "😳",
      "🤪",
      "😵",
      "🥴",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🤧",
      "😇",
      "🥳",
      "🥺",
      "🤠",
      "🤡",
      "🤥",
      "🤫",
      "🤭",
      "🧐",
      "🤓",
      "😈",
      "👿",
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "👐",
      "🤲",
      "🙏",
      "💪",
      "🦾",
    ],
  },
  {
    name: "Animals & Nature",
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐸",
      "🐵",
      "🙈",
      "🙉",
      "🙊",
      "🐒",
      "🐔",
      "🐧",
      "🐦",
      "🐤",
      "🐣",
      "🐥",
      "🦆",
      "🦅",
      "🦉",
      "🦇",
      "🐺",
      "🐗",
      "🐴",
      "🦄",
      "🐝",
      "🪱",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🪲",
      "🪳",
      "🦟",
      "🦗",
      "🕷️",
      "🦂",
      "🐢",
      "🐍",
      "🦎",
      "🦖",
      "🦕",
      "🐙",
      "🦑",
      "🦐",
      "🦞",
      "🦀",
      "🐡",
      "🐠",
      "🐟",
      "🐬",
      "🐳",
      "🐋",
      "🦈",
      "🐊",
      "🐅",
      "🐆",
      "🦓",
      "🦍",
      "🦧",
      "🐘",
      "🌸",
      "💐",
      "🌷",
      "🌹",
      "🥀",
      "🌺",
      "🌻",
      "🌼",
      "🌿",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
      "🌱",
      "🌲",
      "🌳",
      "🌴",
      "🌵",
      "🌾",
      "🌊",
    ],
  },
  {
    name: "Food & Drink",
    emojis: [
      "🍏",
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍈",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      "🍆",
      "🥑",
      "🥦",
      "🥬",
      "🥒",
      "🌶️",
      "🫑",
      "🌽",
      "🥕",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🥐",
      "🥯",
      "🍞",
      "🥖",
      "🥨",
      "🧀",
      "🥚",
      "🍳",
      "🧈",
      "🥞",
      "🧇",
      "🥓",
      "🥩",
      "🍗",
      "🍖",
      "🦴",
      "🌭",
      "🍔",
      "🍟",
      "🍕",
      "🫓",
      "🥪",
      "🥙",
      "🧆",
      "🌮",
      "🌯",
      "🫔",
      "🥗",
      "🥘",
      "🫕",
      "🥫",
      "🍝",
      "🍜",
      "🍲",
      "🍛",
      "🍣",
      "🍱",
      "🥟",
      "🦪",
      "🍤",
      "🍙",
      "🍚",
      "🍘",
      "🍥",
      "🥠",
      "🥮",
      "🍢",
      "🍡",
      "🍧",
      "🍨",
      "🍦",
      "🥧",
      "🧁",
      "🍰",
      "🎂",
      "🍮",
      "🍭",
      "🍬",
      "🍫",
      "🍿",
      "🍩",
      "🍪",
      "🌰",
      "🥜",
      "🍯",
      "☕",
      "🍵",
      "🫖",
      "🧃",
      "🥤",
      "🧋",
      "🍶",
      "🍺",
      "🍻",
      "🥂",
      "🍷",
      "🥃",
      "🍸",
      "🍹",
    ],
  },
  {
    name: "Activities",
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      "🎱",
      "🪀",
      "🏓",
      "🏸",
      "🏒",
      "🏑",
      "🥍",
      "🏏",
      "🪃",
      "🥅",
      "⛳",
      "🪁",
      "🏹",
      "🎣",
      "🤿",
      "🥊",
      "🥋",
      "🎽",
      "🛹",
      "🛼",
      "🛷",
      "⛸️",
      "🥌",
      "🎿",
      "⛷️",
      "🏂",
      "🪂",
      "🏋️",
      "🤼",
      "🤸",
      "🤺",
      "⛹️",
      "🤾",
      "🏌️",
      "🏇",
      "🧘",
      "🏄",
      "🏊",
      "🤽",
      "🚣",
      "🧗",
      "🚵",
      "🚴",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🏅",
      "🎖️",
      "🏵️",
      "🎗️",
      "🎪",
      "🎭",
      "🎨",
      "🎬",
      "🎤",
      "🎧",
      "🎼",
      "🎹",
      "🥁",
      "🪘",
      "🎷",
      "🎺",
      "🪗",
      "🎸",
      "🎻",
      "🎲",
      "♟️",
      "🎯",
      "🎳",
      "🎮",
      "🎰",
      "🧩",
    ],
  },
  {
    name: "Travel & Places",
    emojis: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🏎️",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🛵",
      "🏍️",
      "🛺",
      "🚲",
      "🛴",
      "🚨",
      "🚔",
      "🚍",
      "🚘",
      "🚖",
      "🚡",
      "🚠",
      "🚟",
      "🚃",
      "🚋",
      "🚞",
      "🚝",
      "🚄",
      "🚅",
      "🚈",
      "🚂",
      "🚆",
      "🚇",
      "🚊",
      "🚉",
      "✈️",
      "🛫",
      "🛬",
      "🛩️",
      "💺",
      "🛰️",
      "🚀",
      "🛸",
      "🚁",
      "🛶",
      "⛵",
      "🚤",
      "🛥️",
      "🛳️",
      "⛴️",
      "🚢",
      "🗼",
      "🏰",
      "🏯",
      "🏟️",
      "🎡",
      "🎢",
      "🎠",
      "⛲",
      "⛱️",
      "🏖️",
      "🏝️",
      "🏜️",
      "🌋",
      "⛰️",
      "🏔️",
      "🗻",
      "🏕️",
      "🛖",
      "🏠",
      "🏡",
      "🏢",
      "🏬",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏪",
      "🏫",
      "🏩",
      "💒",
      "🏛️",
      "⛪",
      "🕌",
      "🕍",
      "🛕",
      "🕋",
      "⛩️",
      "🌁",
      "🌃",
      "🌄",
      "🌅",
      "🌆",
      "🌇",
      "🌉",
    ],
  },
  {
    name: "Objects",
    emojis: [
      "⌚",
      "📱",
      "💻",
      "⌨️",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "💽",
      "💾",
      "💿",
      "📀",
      "📼",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "🎞️",
      "📞",
      "☎️",
      "📟",
      "📠",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "🧭",
      "⏱️",
      "⏲️",
      "⏰",
      "🕰️",
      "⌛",
      "⏳",
      "📡",
      "🔋",
      "🔌",
      "🔒",
      "🔓",
      "🔑",
      "💡",
      "🔦",
      "🕯️",
      "🧯",
      "🛢️",
      "💸",
      "💵",
      "💴",
      "💶",
      "💷",
      "🪙",
      "💰",
      "💳",
      "💎",
      "⚖️",
      "🪜",
      "🧰",
      "🪛",
      "🔧",
      "🔨",
      "⚒️",
      "🛠️",
      "⛏️",
      "🪚",
      "🔩",
      "⚙️",
      "🪤",
      "🧲",
      "🔫",
      "💣",
      "🪓",
      "🔪",
      "🗡️",
      "⚔️",
      "🛡️",
      "🚬",
      "⚰️",
      "🪦",
      "🏺",
      "🔮",
      "📿",
      "🧿",
      "💈",
      "⚗️",
      "🔭",
      "🔬",
      "🕳️",
      "🩹",
      "🩺",
      "💊",
      "💉",
      "🩸",
      "🧬",
      "🦠",
      "🧪",
      "🌡️",
      "🧹",
      "🪠",
      "🧺",
      "🧻",
      "🚽",
      "🚰",
    ],
  },
  {
    name: "Symbols",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❤️‍🔥",
      "❤️‍🩹",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "🕉️",
      "☸️",
      "✡️",
      "🔯",
      "🕎",
      "☯️",
      "☦️",
      "🛐",
      "⛎",
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓",
      "🆔",
      "⚛️",
      "🉑",
      "☢️",
      "☣️",
      "📴",
      "📳",
      "🈶",
      "🈚",
      "🈸",
      "🈺",
      "🈷️",
      "✴️",
      "🆚",
      "💮",
      "🉐",
      "㊙️",
      "㊗️",
      "🈴",
      "🈵",
      "🈹",
      "🈲",
      "🅰️",
      "🅱️",
      "🆎",
      "🅾️",
      "🆑",
      "🆘",
      "❌",
      "⭕",
      "🛑",
      "⛔",
      "📛",
      "🚫",
      "💯",
      "💢",
      "♨️",
      "🚷",
      "🚯",
      "🚳",
      "🚱",
      "🔞",
      "📵",
      "🚭",
      "❗",
      "❓",
      "‼️",
      "⁉️",
      "🔅",
      "🔆",
      "〽️",
      "⚠️",
      "🚸",
      "🔱",
      "⚜️",
      "🔰",
      "♻️",
      "✅",
      "🈯",
      "💹",
      "❇️",
      "✳️",
      "❎",
      "🌐",
      "💠",
      "Ⓜ️",
      "🌀",
      "💤",
      "🏧",
      "🚾",
      "♿",
      "🅿️",
      "🛗",
      "🈳",
      "🈂️",
      "🛂",
      "🛃",
      "🛄",
      "🛅",
      "🚹",
      "🚺",
      "🚼",
      "⚧️",
      "🚻",
      "🚮",
      "🎦",
      "📶",
      "🈁",
      "🔣",
      "ℹ️",
      "🔤",
      "🔡",
      "🔠",
      "🆖",
      "🆗",
      "🆙",
      "🆒",
      "🆕",
      "🆓",
      "0️⃣",
      "1️⃣",
      "2️⃣",
      "3️⃣",
      "4️⃣",
      "5️⃣",
      "6️⃣",
      "7️⃣",
      "8️⃣",
      "9️⃣",
      "🔟",
      "🔢",
      "#️⃣",
      "*️⃣",
      "⏏️",
      "▶️",
      "⏸️",
      "⏯️",
      "⏹️",
      "⏺️",
      "⏭️",
      "⏮️",
      "⏩",
      "⏪",
      "⏫",
      "⏬",
      "◀️",
      "🔼",
      "🔽",
      "➡️",
      "⬅️",
      "⬆️",
      "⬇️",
      "↗️",
      "↘️",
      "↙️",
      "↖️",
      "↕️",
      "↔️",
      "↪️",
      "↩️",
      "⤴️",
      "⤵️",
      "🔀",
      "🔁",
      "🔂",
      "🔄",
      "🔃",
      "🎵",
      "🎶",
      "➕",
      "➖",
      "➗",
      "✖️",
      "♾️",
      "💲",
    ],
  },
  {
    name: "Flags",
    emojis: [
      "🏁",
      "🚩",
      "🎌",
      "🏴",
      "🏳️",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🏴‍☠️",
      "🇦🇫",
      "🇦🇱",
      "🇩🇿",
      "🇦🇸",
      "🇦🇩",
      "🇦🇴",
      "🇦🇮",
      "🇦🇬",
      "🇦🇷",
      "🇦🇲",
      "🇦🇼",
      "🇦🇺",
      "🇦🇹",
      "🇦🇿",
      "🇧🇸",
      "🇧🇭",
      "🇧🇩",
      "🇧🇧",
      "🇧🇾",
      "🇧🇪",
      "🇧🇿",
      "🇧🇯",
      "🇧🇲",
      "🇧🇹",
      "🇧🇴",
      "🇧🇦",
      "🇧🇼",
      "🇧🇷",
      "🇧🇳",
      "🇧🇬",
      "🇧🇫",
      "🇧🇮",
      "🇰🇭",
      "🇨🇲",
      "🇨🇦",
      "🇨🇻",
      "🇨🇫",
      "🇹🇩",
      "🇨🇱",
      "🇨🇳",
      "🇨🇴",
      "🇰🇲",
      "🇨🇬",
      "🇨🇩",
      "🇨🇷",
      "🇭🇷",
      "🇨🇺",
      "🇨🇾",
      "🇨🇿",
      "🇩🇰",
      "🇩🇯",
      "🇩🇲",
      "🇩🇴",
      "🇪🇨",
      "🇪🇬",
      "🇸🇻",
      "🇬🇶",
      "🇪🇷",
      "🇪🇪",
      "🇸🇿",
      "🇪🇹",
      "🇫🇮",
      "🇫🇷",
      "🇬🇦",
      "🇬🇲",
      "🇬🇪",
      "🇩🇪",
      "🇬🇭",
      "🇬🇷",
      "🇬🇩",
      "🇬🇹",
      "🇬🇳",
      "🇬🇾",
      "🇭🇹",
      "🇭🇳",
      "🇭🇰",
      "🇭🇺",
      "🇮🇸",
      "🇮🇳",
      "🇮🇩",
      "🇮🇷",
      "🇮🇶",
      "🇮🇪",
      "🇮🇱",
      "🇮🇹",
      "🇯🇲",
      "🇯🇵",
      "🇯🇴",
      "🇰🇿",
      "🇰🇪",
      "🇰🇼",
      "🇱🇧",
      "🇱🇾",
      "🇲🇾",
      "🇲🇽",
      "🇲🇦",
      "🇲🇿",
      "🇳🇱",
      "🇳🇿",
      "🇳🇬",
      "🇳🇴",
      "🇵🇰",
      "🇵🇦",
      "🇵🇪",
      "🇵🇭",
      "🇵🇱",
      "🇵🇹",
      "🇶🇦",
      "🇷🇴",
      "🇷🇺",
      "🇸🇦",
      "🇷🇸",
      "🇸🇬",
      "🇸🇰",
      "🇸🇮",
      "🇿🇦",
      "🇰🇷",
      "🇪🇸",
      "🇱🇰",
      "🇸🇪",
      "🇨🇭",
      "🇹🇼",
      "🇹🇭",
      "🇹🇷",
      "🇺🇦",
      "🇦🇪",
      "🇬🇧",
      "🇺🇸",
      "🇺🇾",
      "🇻🇪",
      "🇻🇳",
    ],
  },
];

/** Default categories enriched with semantic search terms. */
export const DEFAULT_EMOJI_CATEGORIES: readonly EmojiCategory[] =
  DEFAULT_EMOJI_CATEGORY_DATA.map((category) => ({
    ...category,
    searchTerms: DEFAULT_EN_US_EMOJI_SEARCH_TERMS,
  }));
